data:
  train_path: ~
  val_path: ~
  sr: 16000
  duration: 3.17    # {time 3.17: frames 100}
  n_mels: 128
  n_fft: 1024
  train_batchsize: 32
  val_batchsize: 1

model:
  n_classes: 3

train:
  manual_seed: 12138
  lr: 0.01
  momentum: 0.9
  gamma: 0.1
  milestones: [40]
  num_classes: 3

  trainer:
    devices: 1
    accelerator: 'gpu'
    strategy: 'ddp'
    max_epochs: 100

  logging:
    save_dir: "logs/"
    name: 'CantoneseClsLog'



